package dev.gangster.model.protobuf.equipment

import dev.gangster.model.protobuf.common.PBItem
import kotlinx.serialization.Serializable

/**
 * example request: %xt%viewinventory%1%-1%CisIBRACGAIiBgjCAxDWDigBMgUIABCPTkIICAAQGRgAIABaBgiA9SQQAGABCjEIDRABGAQiBgjwFRDIASgAMgUIABCPTjgEUgQIAxACYApoBHIMCBAVCtcjPR3NzMw9CjAIEhABGAQiBQjIBhA8KAAyBQgAEI9OOANSBAgDEAJgA2gAcgwIEhXNzEw9Hc3MTD0KMAgKEAEYBCIFCIgTEHooADIFCAAQj044AlIECAIQAmA9aAByDAgOFc3MTD4dzcxMPgo2CAcQARgEIgYImA0Q0wEoADIFCAAQj044AVIECAMQAmDTAWgAcgwIHxXNzEw9HSlcjz14AXgCChQIABABGAEiBAgAEAAoADIECAAQAAowCAwQARgEIgUIkAcQQigAMgUIABCPTjgEUgQIAxACYAJoAXIMCAoVzcxMPR0AAAAACjEIDxABGAQiBgiQHBD6ASgAMgUIBBCPTjgDUgQIAhADYApoAHIMCBEVAABAPx2PwvU8CjEIDhADGAQiBgi4AxC0BigBMgUIABCPTjgDUgQIAhACYApoAHIMCAsVCtcjPh0AAAAACjQICBABGAQiBgjwDRDeASgAMgUIDRCPTjgBUgQIAxACYN4BaAByDAgfFc3MTD0dKVyPPXgDChQIABABGAEiBAgAEAAoADIECAAQAAoUCAAQARgBIgQIABAAKAAyBAgAEAAKFAgAEAEYASIECAAQACgAMgQIABAAChQIABABGAEiBAgAEAAoADIECAAQAAo2CAkQARgEIgYIoA8Q9AEoADIFCA0Qj044AVIECAMQAmD0AWgAcgwIHxXNzEw9HSlcjz14BHgFChQIABABGAEiBAgAEAAoADIECAAQAAotCAoQARgFIgYI2AQQkBwoATIFCAAQj05SBAgCEAJyDAgHFQrXIz0dAAAAAHgBCiIIDxABGAEiBgigBhDoAigAMgQIChAeOAFCCAgAEBsYACAAChQIABABGAEiBAgAEAAoADIECAAQAAojCJ0BEAEYASIGCKAGEOgCKAAyBAgKEB44B0IICBYQABgAIAAQ6Ac=%
 */
@Serializable
data class PBEquipmentViewInventoryResponse(
    val items: List<PBItem>,
    val unlockCost: Int
) {
    companion object {
        fun empty(): PBEquipmentViewInventoryResponse {
            return PBEquipmentViewInventoryResponse(
                items = emptyList(),
                unlockCost = 100
            )
        }
    }
}
