ktor:
    application:
        modules:
            - dev.gangster.ApplicationKt.module
    development: true
    deployment:
        port: 8080
mongo:
    url: "$MONGO_URL:mongodb://localhost:27017"
game:
